Repository Severson-Group/eMach, pull requests merged in 2019-03, with the labels that each got.

#76 Add multiplication with non-dimensional scalar to operator overloads.
  model_obj/dimensions/DimLinear.m
Labels: architecture

#75 Change add_theta to addTheta in Location2D
  model_obj/Location2D.m
Labels: bug

#68 Add additional MagNet plumbing and porcelain functions
  tools/magnet/plumbing/document/mn_d_makeSimpleCoil.m
  tools/magnet/plumbing/document/problem/mn_dp_getParameter.m
  tools/magnet/plumbing/document/solution/mn_ds_getOhmicLossInConductor.m
  tools/magnet/plumbing/document/solution/mn_ds_getSolvedProblems.m
  tools/magnet/porcelain/mn_findBody.m
  tools/magnet/porcelain/mn_getPathOfRadialFaces.m
  tools/magnet/porcelain/solutionData/mn_getCurveValues.m
  tools/magnet/porcelain/solutionData/mn_getTimeInstants.m
  tools/magnet/porcelain/solutionData/mn_readCircuitCompCurrent.m
  tools/magnet/porcelain/solutionData/mn_readCircuitCompVoltage.m
  tools/magnet/porcelain/solutionData/mn_readCoilCurrent.m
  tools/magnet/porcelain/solutionData/mn_readCoilFluxLinkage.m
  tools/magnet/porcelain/solutionData/mn_readCoilVoltage.m
  tools/magnet/porcelain/solutionData/mn_readCompCurrent.m
  tools/magnet/porcelain/solutionData/mn_readCompVoltage.m
  tools/magnet/porcelain/solutionData/mn_readConductorOhmicLoss.m
  tools/magnet/porcelain/solutionData/mn_readFieldAtPoints.m
  tools/magnet/porcelain/solutionData/mn_readForceOnBody.m
  tools/magnet/porcelain/solutionData/mn_readTorqueOnBody.m
Labels: architecture, enhancement
