Repository Severson-Group/eMach, pull requests merged in 2020-12, with the labels that each got.

#132 Make base function calls explicit
  python/bharat_sandbox/DrawCircleSquare.py
  python/bharat_sandbox/MagnetFunc.py
  python/bharat_sandbox/example.py
  python/emach/test_abc.py
  python/emach/test_ind_funcs.py
  python/emach/tools/magnet/__init__.py
  python/emach/tools/magnet/document/__init__.py
  python/emach/tools/magnet/document/document.py
  python/emach/tools/magnet/document/view.py
  python/emach/tools/magnet/magnet.py
  python/emach/tools/tool_abc/toolabc.py
  python/tools/magnet/emach/__init__.py
  python/tools/magnet/emach/__pycache__/__init__.cpython-38.pyc
  python/tools/magnet/emach/tool_abc/__pycache__/toolabc.cpython-38.pyc
  python/tools/magnet/emach/tool_magnet/__pycache__/__init__.cpython-38.pyc
  python/tools/magnet/emach/tool_magnet/__pycache__/magnet.cpython-38.pyc
  python/tools/magnet/emach/tool_magnet/__pycache__/mn_class.cpython-38.pyc
  python/tools/magnet/emach/tool_magnet/document/__pycache__/__init__.cpython-38.pyc
  python/tools/magnet/emach/tool_magnet/document/__pycache__/doc.cpython-38.pyc
  python/tools/magnet/emach/tool_magnet/document/__pycache__/document.cpython-38.pyc
  python/tools/magnet/emach/tool_magnet/document/__pycache__/view.cpython-38.pyc
  python/tools/magnet/test__pckg_ind_funcs.py
Labels: enhancement, python

#142 Add markdown documentation for python-MAGNET interfacing
  python/tools/magnet/emach/README.md
Labels: enhancement

#157 Add dimension meters
  model_obj/dimensions/DimMeter.m
Labels: enhancement, matlab
