Repository Severson-Group/eMach, pull requests merged in 2021-03, with the labels that each got.

#150 Add python support for Dimensions
  python/emach/examples/example_dimension_unit_test.py
  python/emach/model_obj/__init__.py
  python/emach/model_obj/dimensions/__init__.py
  python/emach/model_obj/dimensions/dim_angular.py
  python/emach/model_obj/dimensions/dim_base.py
  python/emach/model_obj/dimensions/dim_degree.py
  python/emach/model_obj/dimensions/dim_inch.py
  python/emach/model_obj/dimensions/dim_linear.py
  python/emach/model_obj/dimensions/dim_millimeter.py
  python/emach/model_obj/dimensions/dim_radian.py
Labels: python

#177 Add trapezoid crosssect markdown readme and update cross-sect readme instructions
  model_obj/crosssects/README.md
  model_obj/crosssects/trapezoid/CrossSectTrapezoid.pdf
  model_obj/crosssects/trapezoid/CrossSectTrapezoid.svg
  model_obj/crosssects/trapezoid/README.md
Labels: documentation

#166 Add TokenDraw Class
  python/emach/tools/magnet/magnet.py
  python/emach/tools/token_draw.py
Labels: enhancement

#176 Fix Issue #173 , #174 and #175
  python/emach/examples/example_dimension_unit_test.py
  python/emach/model_obj/dimensions/dim_angular.py
  python/emach/model_obj/dimensions/dim_base.py
  python/emach/model_obj/dimensions/dim_linear.py
Labels: python

#190 Update hollow cylinder cross-section
  examples/exampleHollowCylinder.m
  model_obj/crosssects/hollowCylinder/CrossSectHollowCylinder.m
  model_obj/crosssects/hollowCylinder/CrossSectHollowCylinder.svg
  model_obj/crosssects/hollowCylinder/CrossSectHollowCylinderDrawing.pdf
  model_obj/crosssects/hollowCylinder/CrossSectHollowCylinderDrawing.svg
  model_obj/crosssects/hollowCylinder/README.md
Labels: documentation

#185 Make OuterRotorStator crosssect folder compliant with crosssect guidelines
  model_obj/crosssects/outerRotorStator/CrossSectOuterRotorStator.pdf
  model_obj/crosssects/outerRotorStator/CrossSectOuterRotorStator.svg
  model_obj/crosssects/outerRotorStator/README.md
  model_obj/crosssects/outerRotorStator/outerRotorStator.pdf
Labels: documentation

#194 Update breadloaf cross-section
  model_obj/crosssects/breadloaf/Breadloaf.pdf
  model_obj/crosssects/breadloaf/Breadloaf.svg
  model_obj/crosssects/breadloaf/CrossSectBreadloaf.svg
  model_obj/crosssects/breadloaf/README.md
Labels: documentation

#193 Make NotchedRectangle crosssect folder compliant with crosssect guidelines
  model_obj/crosssects/notchedRectangle/CrossSectNotchedRectangle.pdf
  model_obj/crosssects/notchedRectangle/CrossSectNotchedRectangle.png
  model_obj/crosssects/notchedRectangle/CrossSectNotchedRectangle.svg
  model_obj/crosssects/notchedRectangle/README.md
Labels: documentation

#192 Make OuterRotor crosssect folder compliant with crosssect guidelines
  examples/outerRotorExample.m
  model_obj/crosssects/outerRotor/CrossSectOuterRotor.m
  model_obj/crosssects/outerRotor/CrossSectOuterRotor.pdf
  model_obj/crosssects/outerRotor/CrossSectOuterRotor.svg
  model_obj/crosssects/outerRotor/README.md
  model_obj/crosssects/outerRotor/outerRotor.pdf
Labels: documentation
