Repository Severson-Group/eMach, pull requests merged in 2022-06, with the labels that each got.

#161 Fix auto_docs generation on ReadTheDocs site
  docs/source/conf.py
Labels: bug

#165 Add mock imports and specify python ver for RTD
  .readthedocs.yaml
  docs/source/conf.py
Labels: bug, documentation

#167 Edit doc for windage loss analyzer
  docs/source/general_analyzers/windage_loss_analyzer.rst
Labels: documentation

#168 Edit SPM structural analzyer doc
  docs/source/SPM_Analyzers/SPM_structural_analyzer.rst
Labels: documentation

#169 Edit sleeve analyzer
  docs/source/SPM_Analyzers/SPM_sleeve_analyzer.rst
Labels: documentation

#178 Edit language in analyzer docs
  docs/source/general_analyzers.rst
  docs/source/general_analyzers/thermal_res_net_analyzer.rst
Labels: documentation

#179 Enable autodoc for analyzers
  __init__.py
  docs/source/SPM_Analyzers/SPM_structural_analyzer.rst
  docs/source/auto_docs.rst
  docs/source/code_overview.rst
  docs/source/conf.py
  docs/source/general_analyzers/inner_rotor_stator_thermal_analyzer.rst
  docs/source/getting_started/pre_reqs.rst
  docs/source/mach_eval.analyzers.general.rst
  docs/source/mach_eval.analyzers.rst
  docs/source/mach_eval.analyzers.spm.rst
  docs/source/mach_eval.rst
  docs/source/mach_opt.rst
  docs/source/publications.rst
  mach_eval/analyzers/__init__.py
  mach_eval/analyzers/analyzer.py
  mach_eval/analyzers/general/__init__.py
  mach_eval/analyzers/general/thermal_network.py
  mach_eval/analyzers/general/thermal_stator.py
  mach_eval/analyzers/general/windage_loss.py
  mach_eval/analyzers/spm/__init__.py
  mach_eval/analyzers/spm/rotor_structural.py
  mach_eval/analyzers/spm/rotor_thermal.py
  mach_eval/mach_eval.py
Labels: documentation, enhancement

#180 Update contribution guidelines
  docs/source/contribution.rst
  docs/source/index.rst
  environment.yml
Labels: documentation
