Repository Severson-Group/eMach, pull requests merged in 2023-11, with the labels that each got.

#304 turn on numbers for tutorial section
  docs/source/getting_started/tutorials/index.rst
Labels: documentation

#309 Reorder install approach numbers and add interactive window statement
  docs/source/getting_started/pre_reqs.rst
Labels: documentation

#308 Remove valid constraints from get_objectives() function.
  examples/mach_opt_examples/713_mach_ex.py
  examples/mach_opt_examples/cuboid_ex.py
  examples/mach_opt_examples/rectangle_ex.py
Labels: bug

#289 Add Code/Documentation Templates to eMach.readthedocs
  CONTRIBUTING.md
  docs/source/code.rst
  docs/source/contribution.rst
  docs/source/documentation.rst
  docs/source/index.rst
Labels: documentation, enhancement
