Repository Severson-Group/eMach, pull requests merged in 2023-10, with the labels that each got.

#292 Update Corrections to SynR Machine and Analyzer
  docs/source/EM_analyzers/output_SynR_jmag2d_analyzer.csv
  docs/source/EM_analyzers/results_SynR_jmag2d_analyzer.csv
  docs/source/machines/SynR/SynR_op_pt.csv
  docs/source/machines/SynR/SynR_oper_pt.rst
  examples/mach_eval_examples/SynR_eval/SynR_em_post_analyzer.py
  examples/mach_eval_examples/SynR_eval/example_SynR_machine.py
  mach_eval/analyzers/electromagnetic/SynR/SynR_em_analyzer.py
  mach_eval/machines/SynR/SynR_machine_oper_pt.py
Labels: bug, documentation, Machine Evaluation

#293 Add Note to BSPM Optimization Tutorial
  docs/source/getting_started/tutorials/bspm_opti_tutorial/index.rst
Labels: documentation, enhancement, Machine Optimization

#297 Fix ReadTheDocs
  .readthedocs.yaml
  docs/requirements.txt
Labels: bug

#294 Rearrange User Guide Section
  docs/source/index.rst
  docs/source/user_guide/codebase.rst
  docs/source/user_guide/images/AnalysisStepExample.png
  docs/source/user_guide/images/CodeOverview.svg
  docs/source/user_guide/images/DesOptlFlowChart.svg
  docs/source/user_guide/images/MachEval.png
  docs/source/user_guide/images/MachineDesignerProtocols.svg
  docs/source/user_guide/images/MachineEvaluatorProtocols.svg
  docs/source/user_guide/images/desopt_Diagram.svg
  docs/source/user_guide/images/machineDesignerExample.png
  docs/source/user_guide/index.rst
  docs/source/user_guide/mach_eval_overview.rst
  docs/source/user_guide/mach_opt_overview.rst
Labels: documentation

#302 Restructure Index Files to Clean Up Table of Contents
  docs/source/EM_analyzers/index.rst
  docs/source/getting_started/tutorials/index.rst
  docs/source/mechanical_analyzers/index.rst
Labels: documentation
